// Copyright (C) 2024-2026 Ulf Bertilsson
// Generates docs/PARAMETER_REFERENCE.md from the code and checks that the
// committed file matches, so the parameter documentation cannot drift from
// the parameter table, the presentation (display text) laws or the editor
// layout.
//
//   arpsid_parameter_reference_doc_tests <docs/PARAMETER_REFERENCE.md>
//       check mode: fails if the file differs from the generated text
//   arpsid_parameter_reference_doc_tests --write <docs/PARAMETER_REFERENCE.md>
//       regenerates the file (cmake --build <dir> --target arpsid_update_parameter_reference)
//
// Sources of truth
//   name, unit, default, automatable   kParamInfos (source/parameter_ids.h)
//   steps (0 = continuous)             normalizedParamStepCount
//   display text                       choice names from the editor label tables
//                                      (arpsid_editor_labels.h, engine decode
//                                      law), else SidParameterPresentation::
//                                      formatNormalized (the text hosts show)
//   editor tab / section               GUI::EditorLayout (VSTGUI editor)

#include "gui/vstgui/arpsid_editor_labels.h"
#include "gui/vstgui/arpsid_editor_layout.h"

#include "arpsid/core/sid_parameter_presentation.h"
#include "parameter_ids.h"

#include <cctype>
#include <cstdio>
#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

using namespace ArpSID;
namespace L = ArpSID::GUI::EditorLayout;

namespace {

std::string display(int id, float norm) {
    std::string s = Editor::editorValueText(id, norm);
    if (s.empty()) {
        char buf[96] = {};
        if (!SidParameterPresentation::formatNormalized(id, norm, buf, sizeof buf)) return "?";
        s = buf;
    }
    std::string out;
    for (char c : s) {
        if (c == '|') out += "\\|";
        else if (c == '\n') out += ' ';
        else out += c;
    }
    return out;
}

std::string name(int id) {
    const char* n = kParamInfos[static_cast<std::size_t>(id)].name;
    return n && n[0] ? n : "(unnamed)";
}

// Value column: every choice for short stepped lists, else the range.
std::string values(int id) {
    const int steps = static_cast<int>(normalizedParamStepCount(id));
    if (steps == 1) return "off / on";
    if (steps >= 2 && steps <= 8) {
        std::string s;
        for (int i = 0; i <= steps; ++i) {
            if (i) s += ", ";
            s += display(id, static_cast<float>(i) / static_cast<float>(steps));
        }
        return s;
    }
    std::string s = display(id, 0.f) + " … " + display(id, 1.f);
    if (steps > 0) s += " (" + std::to_string(steps + 1) + " steps)";
    return s;
}

struct Placement {
    std::vector<std::string> where; // "TAB / SECTION"
};

std::string generate() {
    std::map<int, Placement> placed;
    std::set<int> gridEdited;
    const auto& tabs = L::tabs();
    for (const auto& tab : tabs) {
        const std::string tabName = GUI::tabSpec(tab.id).displayName;
        for (const auto& row : tab.rows) {
            if (row.heightWeight <= 0.f) break;
            for (const auto& sec : row.sections) {
                if (!sec.title) break;
                for (int p : sec.params) {
                    if (p == L::kEnd) break;
                    placed[p].where.push_back(tabName + " / " + sec.title);
                }
                for (int p = 0; p < kNumParams; ++p)
                    if (L::displayEditsParam(sec.display, p)) gridEdited.insert(p);
            }
        }
    }

    std::ostringstream o;
    o << "# ArpSID parameter reference\n\n"
         "<!-- Generated by source/tests/parameter_reference_doc_tests.cpp. Do not edit by hand:\n"
         "     cmake --build <build-dir> --target arpsid_update_parameter_reference -->\n\n"
         "Every parameter ArpSID exposes to hosts (VST3 parameter ID = AU parameter address =\n"
         "index in `source/parameter_ids.h`). Values are normalized 0..1 on the host side; the\n"
         "**Values** column shows the display text: choice names from the editor's label\n"
         "tables (`source/gui/vstgui/arpsid_editor_labels.h`, which decode like the engine),\n"
         "otherwise the shared presentation layer (`SidParameterPresentation`) that hosts use.\n"
         "Both follow the laws the engine renders with. **Steps** is the host step count (0 = continuous;\n"
         "n = n + 1 discrete values). **Editor** lists where the Windows/Linux VST3 editor\n"
         "places the control (`source/gui/vstgui/arpsid_editor_layout.h`); the macOS editor\n"
         "groups the same parameters on the same tabs.\n\n";

    int user = 0, exempt = 0, automatable = 0;
    for (int id = 0; id < kNumParams; ++id) {
        if (L::isEditorExemptParam(id)) ++exempt;
        else ++user;
        if (kParamInfos[static_cast<std::size_t>(id)].automatable) ++automatable;
    }
    o << "- Parameters: **" << kNumParams << "** (" << automatable << " automatable)\n"
      << "- With an editor control: **" << user << "**; host-driven or read-only: **" << exempt << "**\n\n";

    o << "## Contents\n\n";
    for (const auto& tab : tabs) {
        const std::string t = GUI::tabSpec(tab.id).displayName;
        std::string anchor;
        for (char c : t)
            if (std::isalnum(static_cast<unsigned char>(c))) anchor += static_cast<char>(std::tolower(c));
            else if (c == ' ' || c == '-') anchor += '-';
        o << "- [" << t << "](#" << anchor << ")\n";
    }
    o << "- [Sequencer steps](#sequencer-steps)\n- [Host-driven and read-only parameters](#host-driven-and-read-only-parameters)\n\n";

    // One table per tab, in tab order; a parameter shown on several tabs is
    // listed on each with the other places noted.
    for (const auto& tab : tabs) {
        const std::string tabName = GUI::tabSpec(tab.id).displayName;
        std::vector<std::pair<int, std::string>> rows;
        for (const auto& row : tab.rows) {
            if (row.heightWeight <= 0.f) break;
            for (const auto& sec : row.sections) {
                if (!sec.title) break;
                for (int p : sec.params) {
                    if (p == L::kEnd) break;
                    rows.emplace_back(p, sec.title);
                }
            }
        }
        o << "## " << tabName << "\n\n" << GUI::tabSpec(tab.id).description << "\n\n";
        if (rows.empty()) {
            o << "No host parameters: this tab edits state saved with the project (see "
                 "[VST3_EDITOR.md](VST3_EDITOR.md)).\n\n";
            continue;
        }
        o << "| ID | Parameter | Section | Default | Values | Steps | Also on |\n"
             "|---:|---|---|---|---|---:|---|\n";
        for (const auto& [id, section] : rows) {
            const auto& info = kParamInfos[static_cast<std::size_t>(id)];
            std::string also;
            for (const auto& w : placed[id].where)
                if (w != tabName + " / " + section) also += (also.empty() ? "" : "; ") + w;
            o << "| " << id << " | " << name(id) << (info.automatable ? "" : " (not automatable)") << " | "
              << section << " | " << display(id, info.defaultNorm) << " | " << values(id) << " | "
              << normalizedParamStepCount(id) << " | " << also << " |\n";
        }
        o << "\n";
    }

    o << "## Sequencer steps\n\n"
         "The 32 SEQ steps have three parameters each, edited in the STEPS grid of the SEQ tab\n"
         "(left click raises a note, right click lowers it, shift = octave; click or drag in the\n"
         "VEL and GATE rows to set the level, right click clears).\n\n"
         "| Step | Note ID | Velocity ID | Gate ID | Note default | Note range |\n"
         "|---:|---:|---:|---:|---|---|\n";
    for (int s = 0; s < 32; ++s) {
        const int note = static_cast<int>(kParamSeqStep1Note) + s * 3;
        o << "| " << s + 1 << " | " << note << " | " << note + 1 << " | " << note + 2 << " | "
          << display(note, kParamInfos[static_cast<std::size_t>(note)].defaultNorm) << " | " << values(note) << " |\n";
    }
    o << "\nVelocity and gate are continuous (" << values(static_cast<int>(kParamSeqStep1Note) + 1) << "; "
      << values(static_cast<int>(kParamSeqStep1Note) + 2) << ").\n\n";

    o << "## Host-driven and read-only parameters\n\n"
         "These have no editor control on purpose: they mirror incoming MIDI controllers per\n"
         "channel, report engine state, select presets (the BANK tab and the host's program\n"
         "list drive them) or are legacy mirrors kept for old projects.\n\n"
         "| ID | Parameter | Default | Values | Steps |\n|---:|---|---|---|---:|\n";
    for (int id = 0; id < kNumParams; ++id) {
        if (!L::isEditorExemptParam(id)) continue;
        const auto& info = kParamInfos[static_cast<std::size_t>(id)];
        o << "| " << id << " | " << name(id) << " | " << display(id, info.defaultNorm) << " | " << values(id)
          << " | " << normalizedParamStepCount(id) << " |\n";
    }
    return o.str();
}

} // namespace

int main(int argc, char** argv) {
    const bool write = argc > 2 && std::string(argv[1]) == "--write";
    const std::string path = write ? argv[2] : (argc > 1 ? argv[1] : "docs/PARAMETER_REFERENCE.md");
    const std::string text = generate();
    if (write) {
        std::ofstream out(path, std::ios::binary);
        out << text;
        if (!out) {
            std::fprintf(stderr, "cannot write %s\n", path.c_str());
            return 1;
        }
        std::printf("wrote %s\n", path.c_str());
        return 0;
    }
    std::ifstream in(path, std::ios::binary);
    std::stringstream ss;
    ss << in.rdbuf();
    if (!in || ss.str() != text) {
        std::fprintf(stderr,
                     "FAIL: %s is out of date with the parameter table / presentation / editor layout.\n"
                     "      Regenerate it: cmake --build <build-dir> --target arpsid_update_parameter_reference\n",
                     path.c_str());
        return 1;
    }
    std::puts("parameter_reference_doc_tests PASS");
    return 0;
}
